# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bcdock < Formula
  desc "Official CLI for BCDock - managed Business Central environments on Azure"
  homepage "https://bcdock.io"
  version "0.1.0-rc8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bcdock/cli/releases/download/v0.1.0-rc8/bcdock_0.1.0-rc8_macos_x86_64.tar.gz"
      sha256 "c5af36dbbc1e611fa520c130e98a4736d78305d108aa14fafe63f276e3b6e540"

      define_method(:install) do
        bin.install "bcdock"
        man1.install Dir["man/man1/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bcdock/cli/releases/download/v0.1.0-rc8/bcdock_0.1.0-rc8_macos_arm64.tar.gz"
      sha256 "9747315976b2f7e7e4ece8651c1e848380d3b31ae51ef8e036aceed128624ecd"

      define_method(:install) do
        bin.install "bcdock"
        man1.install Dir["man/man1/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bcdock/cli/releases/download/v0.1.0-rc8/bcdock_0.1.0-rc8_linux_x86_64.tar.gz"
      sha256 "8bb3075207b15f0f6f5a263f3c958d4b8012f8a2f952031f2b8a9749c030c1be"
      define_method(:install) do
        bin.install "bcdock"
        man1.install Dir["man/man1/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bcdock/cli/releases/download/v0.1.0-rc8/bcdock_0.1.0-rc8_linux_arm64.tar.gz"
      sha256 "fe758715f749fd2574baaad808b476ac415fb84f182943151b1b71494b709a0a"
      define_method(:install) do
        bin.install "bcdock"
        man1.install Dir["man/man1/*.1"]
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bcdock version")
  end
end
