# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bcdock < Formula
  desc "Official CLI for BCDock - managed Business Central environments on Azure"
  homepage "https://bcdock.io"
  version "0.5.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bcdock/cli/releases/download/v0.5.6/bcdock_0.5.6_macos_x86_64.tar.gz"
      sha256 "9d730c5026bbb4bafaf6c4755be962edfde9f9c3ef5e31841831b9acc7671fa0"

      define_method(:install) do
        bin.install "bcdock"
        man1.install Dir["man/man1/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bcdock/cli/releases/download/v0.5.6/bcdock_0.5.6_macos_arm64.tar.gz"
      sha256 "bc473ab2a582e2f528338af91d6816523f7d810b28280014d4629f1e3a02474d"

      define_method(:install) do
        bin.install "bcdock"
        man1.install Dir["man/man1/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bcdock/cli/releases/download/v0.5.6/bcdock_0.5.6_linux_x86_64.tar.gz"
      sha256 "b6c641c764354454f029c3363d5afb01197f6de2e8647b70a39d94042f71abef"
      define_method(:install) do
        bin.install "bcdock"
        man1.install Dir["man/man1/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bcdock/cli/releases/download/v0.5.6/bcdock_0.5.6_linux_arm64.tar.gz"
      sha256 "f8632af82fa5757cfd2b0f8631a640250c69752f852598bf7809b343596d98fe"
      define_method(:install) do
        bin.install "bcdock"
        man1.install Dir["man/man1/*.1"]
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bcdock version")
  end
end
