# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bcdock < Formula
  desc "Official CLI for BCDock - managed Business Central environments on Azure"
  homepage "https://bcdock.io"
  version "0.5.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bcdock/cli/releases/download/v0.5.4/bcdock_0.5.4_macos_x86_64.tar.gz"
      sha256 "23292c1156d63a5f8164641a4993640c51154f503504784f72cf4d585673eff0"

      define_method(:install) do
        bin.install "bcdock"
        man1.install Dir["man/man1/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bcdock/cli/releases/download/v0.5.4/bcdock_0.5.4_macos_arm64.tar.gz"
      sha256 "b9458e89e6c3562f32272f4162db9172ae32fe9b6f8a9ed3893f73099c16f27a"

      define_method(:install) do
        bin.install "bcdock"
        man1.install Dir["man/man1/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bcdock/cli/releases/download/v0.5.4/bcdock_0.5.4_linux_x86_64.tar.gz"
      sha256 "8287bb7803ef20d7f830ad4a8d979e63dac2236d8f6883f6f07e5e3c3ffd6ae5"
      define_method(:install) do
        bin.install "bcdock"
        man1.install Dir["man/man1/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bcdock/cli/releases/download/v0.5.4/bcdock_0.5.4_linux_arm64.tar.gz"
      sha256 "940a46dc7adad692d707598644cf64ef8cf222a2378f0a4137b820b806a187fa"
      define_method(:install) do
        bin.install "bcdock"
        man1.install Dir["man/man1/*.1"]
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bcdock version")
  end
end
